imputaciones_all:
    path: /
    defaults: { _controller: BackendBundle:Imputaciones:all }
    methods: GET

imputaciones_hash:
    path: /hash
    defaults: { _controller: BackendBundle:Imputaciones:getHash }
    methods: GET

imputaciones_prov:
    path: /prov/
    defaults: { _controller: BackendBundle:Imputaciones:allProv }
    methods: GET

imputaciones_new:
    path: /new
    defaults: { _controller: BackendBundle:Imputaciones:new }
    methods: POST

imputaciones_edit:
    path: /{id}/edit
    defaults: { _controller: BackendBundle:Imputaciones:edit }
    methods: POST