iva_all:
    path: /
    defaults: { _controller: FrontendBundle:Modulos:iva }
    methods: GET

iva_index:
    path: /{id}
    defaults: { _controller: FrontendBundle:Modulos:iva }
    methods: GET

iva_impositivo:
    path: /{id}/{periodo}
    defaults: { _controller: BackendBundle:Impositivo:iva }
    methods: GET