empresa_all:
    path: /
    defaults: { _controller: "AppBundle:Empresas:all" }
    methods: GET

empresa_new:
    path: /new
    defaults: { _controller: "AppBundle:Empresas:new" }
    methods: POST