BackendBundle\Entity\TblImputProv:
    type: entity
    table: tbl_imput_prov
    indexes:
        FK_IMPUT_idx:
            columns:
                - id_imp
        FK_PROV_IMPU_idx:
            columns:
                - id_prov
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idImp:
            targetEntity: TblImputaciones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_imp:
                    referencedColumnName: id
            orphanRemoval: false
        idProv:
            targetEntity: TblProveedores
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_prov:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
