BackendBundle\Entity\TblProveedores:
    type: entity
    table: tbl_proveedores
    indexes:
        FK_IVA_idx:
            columns:
                - iva
        FK_JURISDICCION_PROV_idx:
            columns:
                - jurisdiccion
        IDX_CUIT_PROV_idx:
            columns:
                - cuit
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        cuit:
            type: bigint
            nullable: true
            options:
                unsigned: false
        activo:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        iva:
            targetEntity: TblSituacionIva
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iva:
                    referencedColumnName: id
            orphanRemoval: false
        jurisdiccion:
            targetEntity: TblJurisdicciones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                jurisdiccion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
