BackendBundle\Entity\TblRubros:
    type: entity
    table: tbl_rubros
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        servicio:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: "0: no es servicio\n1: es servicio"
    lifecycleCallbacks: {  }
