BackendBundle\Entity\TblTiposComp:
    type: entity
    table: tbl_tipos_comp
    indexes:
        FK_COD_COMP_idx:
            columns:
                - cod_comp
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipoComp:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
            column: tipo_comp
        blkExe:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: blk_exe
        blkPerciva:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: blk_perciva
        blkPerciibb:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: blk_perciibb
        blkRet:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: blk_ret
        blkNetos:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: blk_netos
        blkIva:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: blk_iva
        blkTotal:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: blk_total
        blkNograv:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: blk_nograv
        autoiva:
            type: integer
            nullable: false
            options:
                unsigned: false
        autoneto:
            type: integer
            nullable: false
            options:
                unsigned: false
        autototal:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        codComp:
            targetEntity: TblComprobantes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_comp:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
