BackendBundle\Entity\TblUser:
    type: entity
    table: tbl_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        apellido:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        role:
            type: integer
            nullable: true
            options:
                unsigned: false
        activo:
            type: integer
            nullable: true
            options:
                unsigned: false
        createDate:
            type: date
            nullable: true
            column: create_date
    lifecycleCallbacks: {  }
